#!/bin/sh

cd "$OPENSHIFT_REPO_DIR"

### Install node packages ###

# Configuration and paths
export npm_config_cache="$OPENSHIFT_DATA_DIR/npm-cache"
export node_modules_dir="$OPENSHIFT_DATA_DIR/node_modules"
export PATH="$node_modules_dir/.bin:$PATH"

# Link the persistent node modules dir into the repo
ln -s "$node_modules_dir" "$OPENSHIFT_REPO_DIR/node_modules"
npm install
