#!/bin/sh

cd "$OPENSHIFT_REPO_DIR/static"

# Install bundled ruby dependencies
export GEM_HOME="$OPENSHIFT_DATA_DIR/gems"
export GEM_PATH="$GEM_HOME"
scl enable ruby193 'bundle install --deployment --path "$GEM_HOME" --binstubs "$OPENSHIFT_DATA_DIR/bin"'
