# Site settings
title: Rich Wareham
email: rich@richwareham.com
description: "Rich Wareham's personal website"
baseurl: ""
url: ""
twitter_username: richwareham
github_username:  rjw57

# Ignore all the build crap
exclude: ["node_modules", "*.yaml", "*.json", ".*",
          "Gruntfile.js", "README.md", "ATTRIBUTION.md",
          "js/bower_components", "scripts"]

# Explicitly include some files
include: ["publications.json"]

# Build settings
markdown: kramdown
permalink: pretty
