# Site settings
title: Rich Wareham
email: rich@richwareham.com
description: "Rich Wareham's personal website"
baseurl: ""
url: ""
twitter_username: richwareham
github_username:  rjw57

# Build settings
markdown: kramdown
permalink: pretty
