application: richwareham-com
version: 2014-07-28
runtime: python27
api_version: 1
threadsafe: yes

# To stop api_server.py complaining about images API
libraries:
- name: PIL
  version: latest

handlers:

# Top-level URLs
- url: /$
  static_files: _site/index.html
  upload: _site/index\.html

# Misc URLs map directly to their path in _site/.
- url: /
  static_dir: _site

# Files to skip
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*.swp
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?node_modules/.*

