"""Create indices on location log tables

Revision ID: 4a95e0d2e30
Revises: 1c055f0cb61
Create Date: 2014-09-09 08:59:04.090842

"""

# revision identifiers, used by Alembic.
revision = '4a95e0d2e30'
down_revision = '1c055f0cb61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_locations_client_id'), 'locations', ['client_id'], unique=False)
    op.create_index(op.f('ix_locations_timestamp'), 'locations', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_timestamp'), table_name='locations')
    op.drop_index(op.f('ix_locations_client_id'), table_name='locations')
    ### end Alembic commands ###
